# Generated by Django 5.2 on 2025-04-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluchik', '0002_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='square',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='Площадь'),
            preserve_default=False,
        ),
    ]
