# Generated by Django 5.2 on 2025-04-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kluchik', '0003_advertisement_square'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='advertisement_count',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='agent_count',
        ),
    ]
