# Generated by Django 5.2 on 2025-04-16 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluchik', '0004_remove_agency_advertisement_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, '0 — Ужасно'), (1, '1 — Очень плохо'), (2, '2 — Плохо'), (3, '3 — Нормально'), (4, '4 — Хорошо'), (5, '5 — Отлично')], default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
