# Generated by Django 5.2 on 2025-05-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluchik', '0006_alter_advertisement_options_agencysubscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_url',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Изображение'),
        ),
    ]
