# Generated by Django 5.2 on 2025-05-06 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluchik', '0007_remove_photo_image_url_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencysubscription',
            options={'verbose_name': 'Подписка на агенства', 'verbose_name_plural': 'Подписки на агенства'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='advertisement_file',
            field=models.FileField(blank=True, null=True, upload_to='advertisements_files/', verbose_name='Файл объявления'),
        ),
        migrations.CreateModel(
            name='AdvertisementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='advertisement_files/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='kluchik.advertisement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Файл объявления',
                'verbose_name_plural': 'Файлы объявлений',
            },
        ),
    ]
