# Generated by Django 5.2 on 2025-05-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluchik', '0008_alter_agencysubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Внешняя ссылка'),
        ),
    ]
