# Generated by Django 5.2 on 2025-05-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluchik', '0009_advertisement_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
