# Generated by Django 5.2 on 2025-05-27 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluchik', '0011_alter_advertisement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencysubscription',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kluchik.agency', verbose_name='Агентство'),
        ),
        migrations.AlterField(
            model_name='agencysubscription',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки'),
        ),
        migrations.AlterField(
            model_name='agencysubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_ad', 'Новое объявление'), ('ad_update', 'Объявление обновлено'), ('ad_sold', 'Недвижимость продана'), ('ad_rented', 'Недвижимость арендована')], max_length=50, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлено'), ('read', 'Прочитано'), ('archived', 'В архиве')], max_length=50, verbose_name='Статус'),
        ),
    ]
