# Generated by Django 5.2 on 2025-05-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluchik', '0012_alter_agencysubscription_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='kluchik.agency', verbose_name='Агентство'),
        ),
    ]
