# Generated by Django 5.2 on 2025-06-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluchik', '0014_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='agency',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AddField(
            model_name='agency',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
