# Generated by Django 5.2 on 2025-06-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluchik', '0015_agency_description_agency_external_url_agency_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Описание'),
        ),
    ]
